import type { Metadata } from 'next'
import '../globals.css'
import NavBar from '@/components/custom/NavBar'
import { geistMono, geistSans } from '../fonts/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`inline-flex ${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
